googleapis/nodejs-firestore

.appveyor.yml
This fixes the build for Node 4 on Windows, which otherwise fails at installing gRPC.
=> Make AppVeyor run `npm rebuild`.

src/document.js, src/index.js, src/reference.js, src/transaction.js, src/write-batch.js, test/document.js, test/order.js, test/query.js, test/watch.js, test/write-batch.js
Fixes https://stackoverflow.com/questions/46565208/setting-a-documentreference-in-document-on-firestore-nodejs?noredirect=1#comment80108029_46565208
The underlying problem is that the Firebase Admin SDK introduces a cyclic reference that causes us to reach the nesting limit of 20 during the validateDocumentData() call (in the Admin SDK, a 'firestore' property of DocumentReference contains a cyclic reference to itself). 
This PR special cases internal Firestore types to no longer do this traversal and changes all logic that traverses nested maps to ignore Firestore special types.
=> Ignore Firestore types in object traversal

src/reference.js, test/collection.js
This is for Google-internal bug b/67419579:
[Node] .doc(undefined).set() does an add
We should catch "undefined" being passed and say "hey don't do that" not do an add
=> Rejecting 'null' and 'undefined' as arguments for CollectionRef.doc()

package.json, src/convert.js, src/document.js, src/index.js, test/document.js, test/index.js
This adds API JSON format to our internal snapshot_() API as specified by go/api-json (Sorry, this is Google Internal). This format is used by Firebase Functions, and directly exposing it means that the GCF team does not have to worry about our data format.
This was added as a conversion (rather than just adding it to decodeValue), since the logic in watch.js and order.js relies on the Protobuf JS format.
We can potentially get rid of creating the extra copy of the data, but that would mean that the input to snapshot_() gets modified.
=> Handle API JSON format

src/convert.js
This ports https://github.com/firebase/firebase-functions/commit/0647a82fd8e3dce954a7125d17f7a4bec483f48e back to the GCloud SDK.
=> Accept timestamp with missing nanoseconds

src/document.js, test/index.js
Before console.log('' + geoPoint) would print: GeoPoint { _latitude: 11, _longitude: 12 }
Now it prints: GeoPoint { latitude: 11, longitude: 12 }
=> Adding toString() to GeoPoint

src/document.js, src/write-batch.js, test/document.js, test/index.js
This adds validation to reject updates for update("foo", {}, "foo.bar", {}).
=> Reject conflict updates for nested maps

src/index.js, src/reference.js, test/typescript.ts, tsconfig.json, types/firestore.d.ts
This also makes 'ntsc -p .' work with test/typescript.d.ts by removing the source dependency on *.js (as it duplicates the namespace)
Fixes: https://github.com/googleapis/nodejs-firestore/issues/52
=> Adding getCollections() to Typescript typings.

src/document.js, src/write-batch.js, test/document.js
This adds FieldPath validation to update( {} ) and makes sure no invalid characters are used as field paths.
=> Validating object keys in update()

src/reference.js, test/query.js
This adds validation that a query can only start or end at a document that is a direct child of the query's collection.
=> Reject nested values as query boundary

package.json, samples/package.json
This release includes:
- https://github.com/googleapis/nodejs-firestore/pull/57  (breaking due to new validation)
- https://github.com/googleapis/nodejs-firestore/pull/60
- https://github.com/googleapis/nodejs-firestore/pull/62
- https://github.com/googleapis/nodejs-firestore/pull/65
- https://github.com/googleapis/nodejs-firestore/pull/69 (breaking due to new validation)
- https://github.com/googleapis/nodejs-firestore/pull/70
=> Bumping release version to 0.10.0

src/reference.js, test/collection.js
=> Add() needs to enforce that the document doesn't yet exist

src/watch.js, test/watch.js
This hopefully addresses more causes of https://github.com/firebase/firebase-admin-node/issues/119#issuecomment-348008611
=> Retrying without an error code

package.json
GRPC 1.8.0 seems to cause 'Stream Removed' Errors on Firebase Functions: https://github.com/grpc/grpc-node/issues/130
=> Pegging GRPC version to 1.7.1

package.json, src/index.js, src/reference.js, test/collection.js, test/document.js, test/index.js
=> Providing better errors for .doc() and .collection()

package.json
I hope this will help reduce future breakages as those with GRPC 1.8.0 (https://github.com/grpc/grpc-node/issues/130).
=> Only allow patch releases for our dependencies

src/convert.js, src/document.js, test/index.js
It looks like Firebase Functions sometimes send us an Array protobuf that is missing the `values` field altogether, which results in an undefined iterator error.
Fixes https://github.com/googleapis/nodejs-firestore/issues/103
=> Allow Protobuf arrays with unset values

src/index.js, test/transaction.js
Fixes https://github.com/googleapis/nodejs-firestore/issues/110
Note that while the diff is pretty big, the change is pretty small: It  moves the final `.then()` callback to transaction.commit(), rather than overwriting the result of the entire runTransaction() function. This allows us to return the result from a recursive execution.
=> Using Transaction Result from last retry

system-test/firestore.js
The backend change the error message for non-existing documents to say "No document to update". This PR updates our tests.
=> Updating System Test to use the new error message

src/index.js, src/reference.js, test/index.js
This PR exports all public types to allow end user to use them in their code directly, e.g. for instanceof checks.
b/72759064
https://stackoverflow.com/questions/48552183/how-to-get-firestore-documentreference-class
=> Exporting all API types

src/index.js, src/transaction.js, system-test/firestore.js, test/transaction.js, test/typescript.ts, types/firestore.d.ts
This adds support for a Transactions.getAll() call that lets users receive multiple documents in a Transaction, similar to what we already support with Firestore.getAll().
=> Adding Transactions.getAll()

src/transaction.js
This changes the variable name for the "read after write" error message in transactions to what it actually is.
=> Updating variable name for Transactions reads

src/reference.js, system-test/firestore.js, test/query.js
We currently support Strings and DocumentReferences for query.orderBy(FieldPath.documentId()).startAt(...), but only DocumentReferences for the corresponding `where()` call.
Addresses: https://stackoverflow.com/questions/48788805/query-by-documentid-in-firebase-function
=> Accept strings in where(FieldPath.documentId(), ...)

src/document.js, src/reference.js, src/write-batch.js, test/document.js, test/index.js, test/path.js, test/query.js, test/write-batch.js
This PR brings us back to 100% test coverage (which dropped to an all time low of 99% with https://github.com/googleapis/nodejs-firestore/pull/137) and cleans up some test RegExp syntax since we don't enfore line length anymore in tests.
This also moves the Field Path tests to one consolidated place.
Note: The 100% coverage change is 
```
- .update('foo', 'bar', {exists: true}, 'foo');  
+ .update('foo', 'bar', {exists: true});
```
=> 100% Test coverage and misc cleanup

conformance/runner.js, src/write-batch.js, test/document.js
This PR allows the call `set({}, merge:true)` since it can be used to ensure that a document exist on the server.
This came up as a valid use case in an internal discussion (b/73495873 - based on customer feedback in b/73132705).
There is currently a conformance test that rejects this call. I excluded the test and will work with @jba on an update.
=> Allowing empty merge calls

conformance/runner.js, src/transaction.js, src/write-batch.js, test/document.js
This is just a cleanup PR:
- The "conflicting field" error also shows up when a user uses the same field twice in an update call. (update('foo', ..., 'foo', ...). I changed the error message to the one of the Java client as it seems more obvious.
- Updated the Transactions.getAll() sample.
=> Improving error message for multiple conflicting fields

test/order.js
This test now verifies that resource names like path/a, path/b and path-/a are ordered correctly.
=> Fixing order test to verify that we order by components

src/document.js, test/document.js, test/order.js
This fixes https://github.com/googleapis/nodejs-firestore/issues/157
There is an edge case in merge() that the specified example hits. When we parse `'o.c.x': firebase.firestore.FieldValue.delete()`, we replace the entire contents of the current target object with `null`. That means that both `o.b` and `o.c` no longer exist when we try to append to `o.c`. We need to preserve the existing data if the object is non-empty.
This is basically the same fix as #119, but expanded to also apply at any level within an object.
=> Keeping non-empty nested objects

src/document.js, src/validate.js, test/document.js, test/order.js, test/query.js
This addresses https://github.com/googleapis/nodejs-firestore/issues/143
This PR changes two of our error messages:
- When we detect an custom object during serialization, we throw: 'Firestore doesn't support serialization of JavaScript objects that were constructed using the 'new' operator.'
- When we detect an invalid type as method argument, we throw: 'Cannot use object of type "FieldPath" as a Firestore argument.'
There might be much better ways to express this, and the easiest way to figure out if the changes here make sense is to look at the test cases that show these error messages. 
Note that the code tested in `order.js` is not reachable from customer code. The tests exists to allow for 100% coverage (touches line https://github.com/googleapis/nodejs-firestore/blob/463fbfc5f70afa3 …
=> Improved error messages for custom types

package.json, samples/package.json
This release includes:
- [added] Added new `{ mergeFields: ...[] }` option for `.set()` calls that allows specifying the subset of fields you wish to merge (https://github.com/googleapis/nodejs-firestore/pull/173).
- [fixed] All Protobuf files are now loaded from `google-proto-files`, which resolves a known issue for missing files such as `google/api/annotations.proto` (https://github.com/googleapis/nodejs-firestore/issues/175, https://github.com/googleapis/nodejs-firestore/pull/188).
- [changed] Updated all dependencies to ensure that GRPC pre-builds are available (https://github.com/googleapis/nodejs-firestore/issues/185, https://github.com/googleapis/nodejs-firestore/pull/189)
- [changed] Improved startup performance for calls to `new Firestore()` …
=> Preparing the 0.14.0 release

README.md
This helps avoid confusion between `@firebase/firestore` and `@google-cloud/firestore`
Fixes https://github.com/googleapis/nodejs-firestore/issues/186
=> Explain when to use @google-cloud/firestore

.circleci/config.yml, package-lock.json, package.json, samples/package-lock.json
For some reason in this library we install `codecov` in the CI step. In all other libraries it's just a dev dependency. I want to make CI configuration files look as much similar as possible across the packages, hence this change.
=> chore: codecov to dev deps

package-lock.json, package.json, src/index.js, test/index.js
This PR is a fork of https://github.com/googleapis/nodejs-firestore/pull/196 and addresses a performance issue on Google Cloud Functions. Firestore usage on GCF is often read-only - that is, they provide the payload for a DocumentSnapshot and use Firestore only to deserialize this payload. We don't need to initialize the networking stack unless the user ends up writing back to Firestore.
This PR lazy-loads v1beta1 and `@google-cloud/common`.
The PR **also removes `@google-cloud/common-grpc`** (as this also pulls in the GRPC dependency). Unfortunately, this means that we no longer inherit from GrpcService. Is that a problem?
Test code:
```
const start = Date.now();
var Firestore = require('@google-cloud/firestore');
var snapshot = new …
```
=> Lazy-load all GRPC dependencies

package.json
This will be the v0.14.1 release.
Contains:
- [Changed] Reduced the module load time by lazy-loading the network stack.
- [Fixed] Fixed the export type of the `Query` class (#200)
- [Fixed] Firestore now allows storing of objects created with`Object.create(null)` (#193)
I didn't change the package.info in samples/package.json since I can't update the package-lock until after the release is published. Follow up PR coming.
=> Bumping version to 0.14.1

.circleci/config.yml, package.json
Drop Node 4/9 support and disable the linting step (since it uses eslint).
=> Drop Node 4/9 support and Lint pre-submit

test/timestamp.js
The test `Timestamps converted to dates when disabled` was missing `keyFilename`. This PR sets its for all Timestamp tests by default.
=> Adding keyFilename for all tests

src/index.js, test/index.js
Removing an assert that fails the system-tests in the release validation. This assert was just added in https://github.com/googleapis/nodejs-firestore/pull/257
We eventually want to re-work our Project ID detection and can address the TODO at that point.
=> Removing assert that fails the system-tests on CI

.appveyor.yml, .circleci/config.yml, package.json
Moving the GCLOUD_APPLICATION_DEFAULT_CREDENTIALS to environment variables in CicleCI and AppVeyor, which should fix the AppVeyor build.
=> Configuring test credentials for CI environments

.circleci/config.yml
NPM publish needs to install the typescript dependency to be able to publish.
See https://circleci.com/gh/googleapis/nodejs-firestore/7128
=> Allow `npm publish` to use `tsc`

package.json, samples/package.json
Release fix for #271 to allow `noImplicitAny: true`.
=> Bumping Firestore to v0.15.3

src/index.js, src/v1beta1/firestore_client.js, system-test/firestore.js
If we don't pass __dirname, `pkg-up` will use the users source folder instead of ours to extract the package.json.
Fixes https://github.com/googleapis/nodejs-firestore/issues/278
=> Using the package root to find the package.json

conformance/runner.js, src/backoff.js, src/convert.js, src/document.js, src/index.js, src/order.js, src/path.ts, src/reference.js, src/timestamp.js, src/transaction.js, src/validate.js, src/watch.js, src/write-batch.js, system-test/firestore.js, test/backoff.js, test/collection.js, test/document.js, test/index.js, test/order.js, test/path.js, test/query.js, test/timestamp.js, test/transaction.js, test/typescript.ts, test/util/helpers.ts, test/watch.js, test/write-batch.js, tsconfig.json
For arrayUnion()/arrayRemove() I need to import DocumentSnapshot. I was hoping that I could get around the circular import hell with this PR. It turns out that doesn't quite help, but the PR is already written, so I propose we do the `require` to `import` migration either way.
This PR also removes the default exports from our internal modules. We only default export Firestore now.
=> Using import instead of require

protos/firestore_proto_api.d.ts, test/util/helpers.ts
The currently checked-in .d.ts files for Proto types uses Proto3 JSON, but the Node client uses ProtobufJS. The major difference is that ProtobufJS uses Google Timestamps instead of ISO Strings, and that oneof come with a special "valueType" field that denotes the (surprising!) type of the value.
This PR updates the timestamp types in the .d.ts file, as well as the one oneof type that I am using for ArrayUnion/ArrayRemove. I also threw in some new test helpers that use the new proto.
Note: I did try to generate this via the BUILD rule `jspb_proto_library`, but I don't think I was on the right track there. Hence, this PR is manually generated.
=> Adding ProtobufJS support

src/document.js, src/field-value.ts, src/index.js, src/reference.js, src/types.ts, src/write-batch.js, system-test/firestore.js, test/document.js, test/field-value.ts, test/query.js, test/util/helpers.ts, types/firestore.d.ts
This PR adds arrayUnion() and arrayRemove() support to the Node client.
It also fixes the error message that is used in query evaluation. We now return: 
`Argument "value" is not a valid QueryValue. FieldValue.method() can only be used in set(), create() or update().`
since `Argument "value" is not a valid FieldValue. FieldValue.method()...` is a little bit non-sensical.
Unfortunately, this PR still uses the old-style dependency injection.
=> Adding Array Transforms

src/logger.ts, src/write-batch.js, system-test/firestore.js
The backend doesn't return a commitTime anymore (or has never?) if a CommitRequest doesn't contain any commits.
Fixes: https://github.com/firebase/firebase-admin-node/issues/312#issuecomment-408043928
=> Support empty write batches

src/document.js, src/field-value.ts, src/geo-point.ts, src/index.js, src/logger.ts, src/path.ts, src/reference.js, src/serializer.ts, src/timestamp.js, src/watch.js, src/write-batch.js, system-test/firestore.js, test/field-value.ts, test/index.js, test/order.js, test/query.js, test/watch.js
This moves the Protobuf Serialization to its own file and allows us make FieldValue a normal package. As part of this, GeoPoint is now also its own file.
There are no functional changes.
=> Extract the Serializer

protos/README.md, protos/firestore_proto_api.d.ts, protos/firestore_proto_api.js
This changes the Proto type for large numbers to the type we use in code. `pbjs` uses `number|Long`, but we use `number|string`.
I wasn't able to find the right setting in `pbjs` to make it generate the right settings. There is `--force-long ` but no `--force-string`, and I much rather deal with strings in the API than with the Long type (we also use strings in the Web Firestore SDK)
=> Manually editing .d.ts files to use 'string' for large numbers

src/document-change.js, src/index.js, src/reference.js, src/transaction.js, src/watch.js, test/collection.js, test/index.js, test/order.js, test/query.js
This is the last bit of "dependency injection" in the Node client.
The DocumentChange class was moved with no changes.
=> Removing the last bit of dependency injection

src/geo-point.ts, system-test/firestore.js
Fixes https://github.com/firebase/firebase-admin-node/issues/337
Note that the original issue doesn't reproduce for me, but the 'latitude' and 'longitude' itself is defined as optional and can therefore be omitted. We would have caught this with stricter types (as added in this PR).
=> Support empty GeoPoint

package.json
The generated code from Protobuf JS has a dependency on "protobufjs", so we should have one too.
Fixes: https://github.com/firebase/firebase-admin-node/issues/338
=> Adding explicit dependency on ProtobufJS

dev/src/reference.js, dev/system-test/firestore.js, dev/test/query.js, dev/test/typescript.ts, dev/test/watch.js, types/firestore.d.ts
Porting the dogChanges API change from the Web SDK.
=> Making .dogChanges a method

dev/src/index.js, dev/test/index.js
=> Fixed typos: initalization --> initialization

dev/src/index.js, dev/src/v1beta1/firestore_client.js, dev/system-test/firestore.ts, synth.py, tsconfig.json
The newly generated Gapic client drops the custom google-cloud-resource-prefix header. This fixes the generated code.
=> Make sure we don't drop the google-cloud-resource-header

dev/src/index.ts, dev/src/path.ts, dev/src/write-batch.ts, dev/test/backoff.ts, dev/test/document.ts, dev/test/index.ts, dev/test/order.ts, dev/test/path.ts, dev/test/query.ts, dev/test/timestamp.ts, dev/test/transaction.ts, dev/test/typescript.ts, dev/test/util/helpers.ts, dev/test/watch.ts, dev/test/write-batch.ts
This converts all manually created tests to TS. The auto-generated test of the Veneer library remains in JS (gapic-v1beta1.js).
There is still lots of room for cleanup (especially regarding the helper functions), which will come in subsequent PRs.
=> Convert tests to TypeScript

dev/test/backoff.ts, dev/test/collection.ts, dev/test/document.ts, dev/test/index.ts, dev/test/path.ts, dev/test/query.ts, dev/test/timestamp.ts, dev/test/watch.ts, dev/test/write-batch.ts
This uses chai instead of `assert.ok`.
I also removed some API tests that add little value on their own.
=> Retiring assert.ok

dev/conformance/runner.ts, dev/src/backoff.ts, dev/test/backoff.ts, dev/test/document.ts, dev/test/index.ts, dev/test/order.ts, dev/test/path.ts, dev/test/query.ts, dev/test/timestamp.ts, dev/test/transaction.ts, dev/test/watch.ts, dev/test/write-batch.ts
This removes all remaining asserts from the unit tests and replaces them with chai.
=> Removing last bits of asserts

dev/src/index.ts, types/firestore.d.ts
This fixes https://github.com/googleapis/nodejs-firestore/issues/397 and explains the `credentials` properies that can be passed to the SDK.
=>  Add Credentials to JSDoc

dev/src/geo-point.ts, dev/test/index.ts
- This is not in our Mobile API.
- It's not in our TS types.
- We don't have .toString in any other types.
- The next release is already a breaking change.
=> Remove GeoPoint.toString()

dev/src/reference.ts, dev/test/query.ts
We currently fail requests that call .startAt() with no arguments... but we do so deep inside the GRPC layer.
=> Validate that at least one argument is provided for Cursor

dev/conformance/runner.ts, package.json
https://github.com/googleapis/nodejs-firestore/pull/445 copies all necessary proto files under `/protos`.
This PR uses these files and removes the dependency on `google-proto-files`.
=> Remove google-proto-files

dev/src/document.ts, dev/src/index.ts, dev/src/transaction.ts, dev/src/types.ts, dev/src/util.ts, dev/system-test/firestore.ts, dev/test/document.ts, dev/test/index.ts, dev/test/transaction.ts, dev/test/typescript.ts, types/firestore.d.ts
This adds a `ReadOptions` argument to getAll() to allow users to specify a field mask.
I tried to keep the API useable and declared the first argument of the varargs method so that it is known the DocumentReferences have to be passed first.
Fixes: https://github.com/googleapis/nodejs-firestore/issues/42
=> Adding FieldMask support to GetAll()

dev/src/document.ts, dev/src/index.ts, dev/src/path.ts, dev/src/reference.ts, dev/src/validate.ts, dev/src/write-batch.ts, dev/test/collection.ts, dev/test/document.ts, dev/test/field-value.ts, dev/test/index.ts, dev/test/order.ts, dev/test/path.ts, dev/test/query.ts, dev/test/timestamp.ts, dev/test/transaction.ts, dev/test/watch.ts, dev/test/write-batch.ts
Fixes https://github.com/googleapis/nodejs-firestore/issues/436 and https://b.corp.google.com/issues/78932093
This PR:
- adds the field path to the error message if a field-level validation fails
- uses consistent quotes in all errors (changed single quotes to double)
- enforces that all errors are verified as they are raised by removing the RegExp matching and matching by exact value instead
=> Slightly better error messages

dev/protos/update.sh, package.json, samples/package.json
This prepares the next Node release and also reformats the `update.sh` file. We don't want to send out a PR with unrelated changes after all.
=> Bumping version to 0.19

dev/src/reference.ts, dev/test/query.ts
This adds the 'array-contains' operator the an error message that validates query operators.
=> Adding array-contains to error message

dev/src/index.ts, dev/src/transaction.ts, dev/system-test/firestore.ts, types/firestore.d.ts
Fixes #501
This PR overloads the getAll function in Firestore and Transaction class to allow passing in a destructured array of documents.
=> Overload getAll function to allow array destructuring

dev/conformance/runner.ts, dev/src/document.ts, dev/src/index.ts, dev/src/path.ts, dev/src/serializer.ts, dev/test/timestamp.ts, package.json
This is part of #512 but can be reviewed independently.
This PR removes the dependency on `is` and moves all checks into the SDK itself. While `is` is nice library, it doesn't quite work with TypeScript type inference.
=> Cleanup: Remove `is`

dev/src/field-value.ts, dev/src/index.ts, dev/src/path.ts, dev/src/reference.ts, dev/src/transaction.ts, dev/src/validate.ts, dev/src/write-batch.ts, dev/test/document.ts, dev/test/query.ts
This is part of https://github.com/googleapis/nodejs-firestore/pull/512 but can be reviewed independently.
This PR adds free-standing methods for argument count validation. The existing methods are removed in a follow-up PR that will remove the entire Validator class.
=> Cleanup: Argument count validation

dev/src/convert.ts, dev/src/geo-point.ts, dev/src/index.ts, dev/src/logger.ts, dev/src/path.ts, dev/src/reference.ts, dev/src/timestamp.ts, dev/src/util.ts, dev/src/validate.ts
This is part of #512 but can be reviewed independently.
This PR adds free-standing methods for the validation of simple types, such as boolean and strings. It uses an function argument to allow for optional values, instead of encoding this behavior in the method name (`isOptionalString` becomes `validateString(..., { optional: true )`.
The unused methods are removed in a follow-up PR.
=> Cleanup: Validate primitive types

dev/src/document.ts, dev/src/index.ts, dev/src/order.ts, dev/src/reference.ts, dev/src/serializer.ts, dev/src/transaction.ts, dev/test/document.ts, dev/test/order.ts, dev/test/watch.ts
This is part of #512  but can be reviewed independently.
This is the random cleanup for all unrelated changes. Note: `serializer` is now types as `Serializer|null` since `Firestore` is no longer `any`.
=> Cleanup: Misc

dev/src/validate.ts
This is part of #512 but can be reviewed independently.
This simplifies the error message generation for custom objects a little.
=> Cleanup: Error messages for custom objects

CHANGELOG.md, package.json, samples/package.json
=> Release @google-cloud/firestore v0.20.0

CHANGELOG.md, package.json, samples/package.json
Release the update to google-gax, to fix proxy issue: https://github.com/googleapis/nodejs-firestore/issues/493
=> Release @google-cloud/firestore v0.21.0

README.md
This adds a section to the Readme advising that this client can't be used with Firestore instances in Datastore mode.
Fixes https://github.com/googleapis/nodejs-firestore/issues/459
=> Add note about Datastore mode

dev/conformance/runner.ts, dev/src/convert.ts, dev/src/document-change.ts, dev/src/document.ts, dev/src/external-modules.d.ts, dev/src/field-value.ts, dev/src/geo-point.ts, dev/src/index.ts, dev/src/logger.ts, dev/src/path.ts, dev/src/reference.ts, dev/src/serializer.ts, dev/src/timestamp.ts, dev/src/types.ts, dev/src/watch.ts, dev/src/write-batch.ts, dev/system-test/firestore.ts, dev/test/backoff.ts, dev/test/collection.ts, dev/test/document.ts, dev/test/index.ts, dev/test/order.ts, dev/test/query.ts, dev/test/timestamp.ts, dev/test/transaction.ts, dev/test/util/helpers.ts, dev/test/watch.ts, dev/test/write-batch.ts, tsconfig.json
This removes `no-implicit-any` from the SDK.
Fixes: https://github.com/googleapis/nodejs-firestore/issues/525
=> refactor(typescript): enable noImplicitAny

dev/system-test/firestore.ts
In #553, I added type information to `DeferredPromise`. As part of this, I changed the initialization in the constructor to `Promise.reject()` since I no longer know the value type. Turns out that that logs a bunch of "unhandled promise rejection" warnings. This PR makes the Promise nullable and defers the initialization. It's not the cleanest solution, but it's test-only code that isn't reused...
=> Remove unhandled Promise rejection warning

dev/test/order.ts
#564 makes `Serializer.encodeValue()` synchronous.
This is a dumb PR to add no-op async/await to the current `test/order.ts`. It is meant to make #564 smaller.
=> Introduce async/await to test/order.ts

dev/src/reference.ts, dev/src/watch.ts, dev/test/watch.ts
This is part of https://github.com/googleapis/nodejs-firestore/pull/564
The changes in #564 to make `formattedName()` async changed a lot of the timing in the Watch code and uncovered an issue with the way we close streams. We should only call `stream.end()` if the SDK closes the stream. If the server closes the stream we don't call end() - if we do, we get an exception (that was previously swallowed).
This PR also introduces subclasses for Watch that provide the Target Proto and the Comaprator. This makes it possible to construct these after initialization time and to return a Promise.
=> Don't call stream.end() on Watch ended by server

dev/src/util.ts
Fixes #574.
The `toString()` call on an async function produces [object AsyncFunction] instead of [object Function]. This PR replaces the toString() check with the same typeof check we use in the Web SDK, which returns "function" for both. See https://github.com/lodash/lodash/issues/2768 for other examples of the same issue.
Note: The lack of tests in this PR is due to the fact that we still support Node 6 and don't use async/await in the transpiled code. It is therefore impossible to write an async Function that would trigger this failure.
=> [fix]: allow async functions in transactions

dev/src/index.ts
Fixes https://github.com/googleapis/nodejs-firestore/issues/599
=> docs: Add example for Precondition

dev/src/index.ts, dev/src/reference.ts, dev/src/transaction.ts, dev/system-test/firestore.ts, dev/test/query.ts, dev/test/typescript.ts, types/firestore.d.ts
CollectionGroup queries add support for queries to Firestore that query documents by collection ID rather than by collection path. With this feature, users can now query for documents in collections that share a name, no matter where these collection are located.
This the Node port of https://github.com/googleapis/google-cloud-java/pull/4652. The integration tests are ported from https://github.com/firebase/firebase-js-sdk/pull/1440
Note: This PR is blocked on a backend release.
=> feature: Adding CollectionGroup queries

dev/src/index.ts, dev/src/pool.ts
Fixes firebase/firebase-admin-node#499
Previously _initializeStream returned a Promise that indicated that the
stream was "released", i.e. that it was was ready for attaching
listeners.
googleapis/nodejs-firestore#256 Added pooled clients and changed the
callers of _initializeStream to reuse this promise such that when it was
resolved, the stream could be returned to the pool. This works when
listeners are short-lived, but fails when listeners run indefinitely.
This change arranges to release the clients back to the pool only after
the stream has completed, which allows an arbitrary number of indefinite
listens to run without problems.
This turns out to be fiendishly difficult to test given the current structure
of the code. A second pass at this that reformulates this as just another …
=> fix: Fix client pooling for long-lived listens

samples/quickstart.js, samples/system-test/quickstart.test.js
To avoid confusion, I think we should remove the `Document created` console output since `firestore.doc()` merely returns a reference. It does not talk to the backend.
=> [docs] Further improve quickstart.js

dev/src/index.ts, dev/src/reference.ts, dev/test/document.ts, dev/test/index.ts, dev/test/typescript.ts, types/firestore.d.ts
BREAKING CHANGE: This removes the deprecated getCollections() method (deprecated in Oct 2018). This will be part of the v2 release.
=> refactor(deprecation)!: remove deprecated getCollections()

dev/src/index.ts, dev/src/pool.ts, dev/src/util.ts, dev/system-test/firestore.ts, dev/test/collection.ts, dev/test/document.ts, dev/test/index.ts, dev/test/order.ts, dev/test/pool.ts, dev/test/query.ts, dev/test/util/helpers.ts, dev/test/watch.ts, dev/test/write-batch.ts, package.json
Fixes firebase/firebase-admin-node#499
This is a different approach to https://github.com/googleapis/nodejs-firestore/pull/614 and solves the same problem. It re-uses more of the original code to achieve the same result. Instead of releasing the client back to the pool when a stream is marked as established, we instead keep it around until the stream is closed.
=> fix: Support more than 100 long-lived streams

dev/conformance/runner.ts, dev/src/index.ts, dev/src/path.ts, dev/src/transaction.ts, dev/test/index.ts, package.json
BREAKING CHANGE: This removes the ability to call getAll() and `new FieldPath()` with an array as its first argument instead of calling it with a list of arguments.
=> refactor(deprecation)!: remove legacy support for array arguments

package.json
Updating Minimum Node version to match GRPC JS
BREAKING CHANGE: library now requires Node >= 8.13.0
=> build!: upgrade engines field to >=8.13.0

dev/src/document.ts, dev/src/write-batch.ts, package.json
We merged https://github.com/googleapis/nodejs-firestore/pull/628 and should now be able to unpin JSDoc.
=> Revert "fix(docs): revert jsdoc and pin to 3.5.5"

dev/src/backoff.ts, dev/src/watch.ts, dev/test/backoff.ts, dev/test/watch.ts
Fixes https://github.com/firebase/firebase-admin-node/issues/478
=> fix: retry on abort and limit retry count to 10

dev/src/reference.ts, dev/test/collection.ts, types/firestore.d.ts
This addresses the same issue as https://github.com/googleapis/nodejs-firestore/pull/658, but instead of relaxing our `CollectionReference.doc()` API, it fixes the types to reflect the invariant that we enforce via our argument validation. As in older releases, we still prevent users from passing "undefined", but with this PR this should generate a compile time error.
This is based on the following little experiment:
```
interface Foo {
bar(): void;
bar(baz: string): void;
}
class Foobar implements Foo {
bar(baz?: string) {}
}
function createFoo(): Foo {
return new Foobar();
}
const f = createFoo();
f.bar();
f.bar("foobar");
f.bar(undefined); // Compile error
```
Note that I am marking this as a "fix" rather than as a "breaking change" as any user that tried to use "undefined" before …
=> fix: Add overloads for doc() and doc(id:string)

package.json
It looks like stream can end prematurely in @gprc/grpc-js 0.4.1. This happens gracefully, resulting in fewer than expected results from a RunQueryRequest.
Addresses https://github.com/googleapis/nodejs-firestore/issues/667
=> deps: Pin @gprc/grpc-js to 0.4.0

package.json
Reverts googleapis/nodejs-firestore#668. `@gprc/grpc-js` released 0.4.2 which contains a fix for https://github.com/grpc/grpc-node/issues/895
Fixes https://github.com/googleapis/nodejs-firestore/issues/661
=> deps: Un-pin @gprc/grpc-js

dev/src/index.ts, dev/src/reference.ts, dev/src/serializer.ts, dev/src/transaction.ts, dev/src/util.ts, dev/test/document.ts, dev/test/util/helpers.ts, dev/test/write-batch.ts
The changes in this PR should let us migrate to TypeScript 3.5, unblocking https://github.com/googleapis/nodejs-firestore/pull/666
See the first two items in https://devblogs.microsoft.com/typescript/announcing-typescript-3-5/#breaking-changes for context
=> style: Prepare for Typescript 3.5 migration

dev/src/index.ts, dev/src/util.ts
I think https://github.com/googleapis/nodejs-firestore/pull/680 doesn't split the `settings.host` correctly into `port` and `servicePath`. We only do this for FIRESTORE_EMULATOR_HOST.
=> fix: Split settings.host into servicePath and port

dev/system-test/firestore.ts, package.json
Updates google-gax to 1.1.2 to pull in https://github.com/googleapis/gax-nodejs/pull/521  and adds tests to verify that we can query non-Ascii collection.
=> fix: Support non-ISO-8859-1 Collection Names in Queries

dev/src/watch.ts
Fixes #661.
We use a single long-lived stream for all of our logic. If the backend streams drops, we unpipe the old stream and pipe and new stream. After many re-connects, it seems to cause EventEmitter leaks (#661). By using new streams rather than piping/unpiping a long-lived stream, the `MaxListenersExceededWarning` should no longer appear.
=> fix: Use new stream rather than pipe

dev/src/index.ts, dev/test/index.ts
Fixes https://github.com/googleapis/nodejs-firestore/pull/696#issuecomment-505822099
=> fix: Relax validation of FIRESTORE_EMULATOR_HOST in settings()

dev/system-test/firestore.ts
This maybe (hopefully?) fixes the flaky system test.
We currently verify at the end of each tests that no more streams are running. The change here is that for `handles more than 100 concurrent listeners` will also wait for the document write to succeed. 
Background: Since all operations are async, it is possible that Watch tells us about a write before we get the write acknowledgment. If that is the case, in the old test, we could tear down the watch streams and exist the test while the write stream is still open.
Fixes: https://github.com/googleapis/nodejs-firestore/issues/708
=> test: Fix flaky system test

dev/src/index.ts, dev/src/pool.ts, dev/src/reference.ts, dev/src/transaction.ts, dev/src/watch.ts, dev/src/write-batch.ts, dev/test/index.ts, dev/test/pool.ts
This PR logs when we create or delete instances in the client pool, helping us debug https://github.com/firebase/firebase-admin-node/issues/620
Almost everything here is related to plumbing through the "request tag"
=> fix: add logging to client pool

dev/src/v1/firestore_client_config.json
Retrying INTERNAL errors for Idempotent calls should help address https://github.com/firebase/firebase-functions/issues/536
=> fix: retrying 13 INTERNAL RPC errors

dev/src/validate.ts, dev/test/document.ts
This PR extends the custom errors for instances of FieldValue classes that do not match the expected prototype to the FieldValue sentinel classes FieldTransform, ServerTimestampTransform, ArrayUnionTransform, ArrayRemoveTransform and NumericIncrementTransform.
Fixes https://github.com/googleapis/nodejs-firestore/issues/760
=> fix: provide custom error for FieldValue subclasses

dev/src/index.ts, dev/src/serializer.ts, dev/src/types.ts, dev/test/index.ts, dev/test/timestamp.ts, dev/test/typescript.ts, types/firestore.d.ts
The next release will be breaking (see https://github.com/googleapis/nodejs-firestore/pull/805). I would like to use this opportunity to clean up the code and remove timestampInSnapshots
=> feat!: remove deprecated timestampInSnapshots setting

dev/src/reference.ts, dev/test/collection.ts, dev/test/document.ts, dev/test/index.ts
This increases the page size from 20 (default) to 300 (max).
Fixes https://github.com/googleapis/nodejs-firestore/issues/825
=> fix: reduce overhead for listDocuments()/listCollections()

dev/src/index.ts, dev/src/pool.ts, dev/src/types.ts, dev/test/index.ts, dev/test/pool.ts, dev/test/typescript.ts, dev/test/util/helpers.ts, dev/test/watch.ts, types/firestore.d.ts
This PR lets users influence the memory profile of their Firestore usage:
- They can set the minimum client pool size to 0 to close all GRPC channels when Firestore is completely idle
- They can use a larger number to reduce the startup costs of new GRPC channels.
This PR aims to preserve the current behavior by always leaving at least one GRPC channel if no option is provided.
b/146363799
=> feat: allow specifying how many idle GRPC channels to keep

dev/test/index.ts
This should make our CI less flaky.
=> fix: increase test timeout

dev/src/external-modules.d.ts, dev/src/index.ts, dev/src/reference.ts, dev/src/watch.ts, dev/system-test/firestore.ts, dev/test/index.ts, dev/test/watch.ts, package.json
This PR removes the dependency on `bun`, which exposed an old Stream interface that did not expose Symbol.asyncInterator. 
A lot of the code churn in this PR is combining `readStream` and `readWriteStream`, which were almost identical before (readStream sent request to the GAPIC method directly, whereas readWriteStream sent it to the stream). The new method handles all Stream callbacks uniformly and combines both stream modes. 
A disclaimer: I don't really understand Node streams, but we have semi-good test coverage for most error cases.
Fixes https://github.com/googleapis/nodejs-firestore/issues/789
=> feat: add Symbol.asyncInterator to Query.stream()

dev/src/serializer.ts, dev/src/validate.ts, dev/test/document.ts
This fixes some slight ambiguity around field name validation error messages as mentioned in #858
Fixes https://github.com/googleapis/nodejs-firestore/issues/858
=> fix: add quotes to field name validation to avoid ambiguity

dev/src/index.ts, dev/test/index.ts, dev/test/pool.ts
Addresses https://github.com/googleapis/nodejs-firestore/issues/829
I think there is a potential problem with stream retry in the existing client. I wasn't able to write a test that hit the scenario, but I can try to put it into words.
In the existing code, requestStream() takes a client object out of the client pool and then calls retry(). There are two Promises that manage all the logic: Result and Lifetime. Since there are separate, it is possible that result.reject() is called (causing a retry) just before lifetime.resolve() is called, which returns the client back to the pool. We then retry with a client that was already returned to the pool, which - if the use is unlucky - is a client that was already garbage collected.
The change in this PR reverses the order: Each retry attempt …
=> fix: do not release client before retry

dev/src/logger.ts
Fixes https://github.com/googleapis/nodejs-firestore/issues/871
=> fix: don't format log message if logging is disable

dev/src/serializer.ts
fixes https://github.com/googleapis/nodejs-firestore/issues/892
=> fix: do not assume all custom objects have constructors

types/firestore.d.ts
Fixing issue with missing generics on the `firestore.d.ts` file. 
Original issue was posted in the firebase-js-sdk: https://github.com/firebase/firebase-js-sdk/issues/2601
=> fix: add missing generics on query

dev/src/index.ts, dev/src/types.ts, dev/test/typescript.ts, types/firestore.d.ts
=> feat: add google-gax status to exports

dev/src/reference.ts, dev/src/write-batch.ts, dev/system-test/firestore.ts, dev/test/collection.ts
Fixes #924 
Needed to convert data toFirestore first before performing validation. Also modified system test to use `CollectionReference.add()`.
=> fix: collectionReference.add() validation

dev/src/reference.ts, dev/test/query.ts
Reported in this [comment](https://github.com/googleapis/nodejs-firestore/issues/924#issuecomment-5872254330).
We previously were dropping the converter when calling `with()`, which meant that the return type would be typed `T` even though the underlying object was still `DocumentData`
=> fix: propagate converter in QueryOptions.with()

dev/src/index.ts, dev/src/pool.ts, dev/src/watch.ts, dev/system-test/firestore.ts, dev/test/pool.ts
Fixes #913 
Implemented the 2nd suggestion. I think it makes more sense to allow for existing operations to complete before calling terminate. In the user's repro it would be strange to have `close()` throw an error.
=> fix: wait for operations to complete before deleting clients

dev/src/timestamp.ts, dev/test/timestamp.ts, types/firestore.d.ts
This enables Timestamp objects to be compared for relative ordering using the <, <=, >, and >= operators.
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #944
=> feat: implement Timestamp.valueOf() (#944)

dev/src/timestamp.ts
=> refactor: use constants for MIN_SECONDS and MAX_SECONDS in Timestamp

dev/src/v1/firestore_admin_client.ts, dev/src/v1/firestore_client.ts, dev/src/v1beta1/firestore_client.ts, dev/synth.metadata, dev/test/gapic-firestore-v1.ts, dev/test/gapic-firestore-v1beta1.ts, dev/test/gapic-firestore_admin-v1.ts
This PR includes changes from https://github.com/googleapis/gapic-generator-typescript/pull/317
that will move the asynchronous initialization and authentication from the client constructor
to an `initialize()` method. This method will be automatically called when the first RPC call
is performed.
The client library usage has not changed, there is no need to update any code.
If you want to make sure the client is authenticated _before_ the first RPC call, you can do
```js
await client.initialize();
```
manually before calling any client method.
=> feat: deferred client initialization

dev/src/transaction.ts, dev/system-test/firestore.ts, dev/test/transaction.ts
This PR implements consistent retry behavior all transaction methods:
As per go/transaction-retry-matrix, it implements the following behavior by error code and RPC:
**RPC: BeginTransaction, Rollback**
- Implicit retry for DEADLINE_EXCEEDED, INTERNAL and UNAVAILABLE with backoff (not in this PR since this is done by google-gax)
**RPC: RunQuery, BatchGetDocuments, Commit**
- Restart transaction for ABORTED (no backoff).
- Restart transaction for CANCELLED, UNKNOWN, DEADLINE_EXCEEDED, INTERNAL, UNAVAILABLE, UNAUTHENTICATED,  RESOURCE_EXHAUSTED (with backoff). 
- Use maximum backoff for RESOURCE_EXHAUSTED.
A restart consists of a rollback and a BeginTransaction RPC with a `retryTransaction`.
I also updated the test cases to allow us to verify the backoff behavior.
Fixes …
=> feat: base transaction retries on error codes

package.json
@JustinBeckwith Since we use our own manually generated types, does the reason for not updating all of GCloud to a newer TypeScript version apply to us?
=> deps: update TypeScript

dev/src/reference.ts, dev/system-test/firestore.ts, dev/test/query.ts, dev/test/typescript.ts, types/firestore.d.ts
Fixes https://github.com/googleapis/nodejs-firestore/issues/945
This adds support for limitToLast(), including order reserving for queries. Fortunately, Watch uses its own comparator, so we don't have to reverse the results in Watch.
=> feat: add support for Query.limitToLast()

dev/src/reference.ts, dev/system-test/firestore.ts, dev/test/query.ts
This fixes a regression introduced in 3.7
Fixes https://github.com/googleapis/nodejs-firestore/issues/969
=> fix: support Query.stream() as first client operation

dev/src/util.ts
Switch to use random number generator from `crypto` to reduce potential conflicts
=> Use Random Number from `crypto` to generate AutoId.

README.md, dev/src/reference.ts, dev/system-test/firestore.ts, dev/test/query.ts
This ports the validation from Web.
Fixes https://github.com/googleapis/nodejs-firestore/issues/990
=> fix: support array of references for IN queries

dev/src/index.ts
Found this while adding docs for BulkWriter. Technically it should be `res[0].writeTime`, but I changed it to be in sync with the code sample from WriteBatch.
=> docs: change batch() code sample

dev/src/rate-limiter.ts, dev/test/rate-limiter.ts
Adding a rate limiter that implements [token bucket](https://www.linkedin.com/pulse/api-rate-limiting-using-token-bucket-algorithm-siddharth-patnaik/) that calculates if a request containing a number of writes can be made under a rate limit as well as the time required before a request can be made while staying under the limit.
It's a little more verbose than I wanted, but having a separate rate limiter has a few benefits for BulkWriter:
- We would not have to log sendTimes for each batch
- We would not have to manually calculate the number of writes made in the past second each time we want to determine whether a batch can be sent.
- Simplifies calculation for the required delay before the next batch can be sent.
Implementation notes:
- I used a `currentTime` parameter to make testing …
=> feat: add rate limiter class

dev/src/index.ts, dev/src/reference.ts, package.json
Drops dependency on through2 (though dev dependency remains). Also drops readable-stream as Node10 supports async iterator out of the box.
=> deps: drop through2

dev/src/bulk-writer.ts, dev/src/index.ts, dev/test/bulk-writer.ts, types/firestore.d.ts
Moving from the old [PR](https://github.com/googleapis/nodejs-firestore/pull/988) to create a base version without bin packing of writes or the 555 throttling.
=> feat: Add BulkWriter base

dev/protos/firestore_admin_v1_proto_api.d.ts, dev/protos/firestore_admin_v1_proto_api.js, dev/protos/firestore_v1_proto_api.d.ts, dev/protos/firestore_v1_proto_api.js, dev/protos/firestore_v1beta1_proto_api.d.ts, dev/protos/firestore_v1beta1_proto_api.js, dev/protos/update.sh, dev/src/convert.ts, dev/src/index.ts, dev/src/serializer.ts, dev/src/timestamp.ts, dev/src/types.ts, dev/system-test/firestore.ts, dev/test/document.ts, dev/test/util/helpers.ts, synth.metadata, types/firestore.d.ts
This PR adds support for serializing to BigInt and for deserializing to BigInt (optional, via flag). We still need to settle on a flag name.
Fixes https://github.com/googleapis/nodejs-firestore/issues/872
=>  feat: support BigInt

dev/src/backoff.ts, dev/src/bulk-writer.ts, dev/src/index.ts, dev/src/rate-limiter.ts, dev/src/types.ts, dev/test/bulk-writer.ts, types/firestore.d.ts
Adding throttling. 
I tried to write the tests as cleanly as I could without overriding too much. Since `RateLimiter` already has tests, I only tested that the timeout handler in BulkWriter was being called. The test will fail with an assertion if throttling is not in place. However, I fear that this test can be brittle if another part of the SDK calls a timeout. Any ideas/tips on how to improve this test? Thanks!
=> feat: add 555 rule support

dev/src/bulk-writer.ts, dev/test/bulk-writer.ts
Forgot to add this earlier. I also didn't realize it would be this little work.
=> Add converter support

.github/workflows/ci.yaml, dev/protos/firestore_admin_v1_proto_api.js, dev/protos/firestore_v1_proto_api.js, dev/protos/firestore_v1beta1_proto_api.js, dev/protos/update.sh, synth.metadata
Work around a bug in `pbjs` (seems to not like nested directories) and run `synthtool`.
=> chore: run synthtool

dev/src/reference.ts, dev/test/query.ts
This makes sure that we return an error from the Query stream() even if we were able to deliver an initial set of query results.
Fixes  https://github.com/googleapis/nodejs-firestore/issues/964
=> fix: return errors from Query.stream()

dev/src/index.ts, dev/src/reference.ts
Looking at the docs, I realized that `FirestoreDataConverter` was nowhere to be found since I didn't include it in `index.ts`. I added links to it in each the `withConverter` `@param` definitions as well. However, I'm not sure how to properly include the method docs for to/fromFirestore in JSdoc without actually writing out code for the interface. I included the methods as `@property`, which isn't ideal but is better that nothing.
=> docs: Add documentation for FirestoreDataConverter

dev/src/types.ts
ts-node is not able to resolve the FirebaseFirestore namespace. It only exists in our types.
=> fix: allow running source with ts-node

dev/src/rate-limiter.ts, dev/test/rate-limiter.ts
Oops. Ran into this while porting rate limiter.
=> fix: incomplete expect in rate-limiter test

dev/src/path.ts, dev/src/reference.ts, dev/system-test/firestore.ts, dev/test/collection.ts
We need to return "null" for the parent call in a root collection.
Also noticed that our Path.isEqual doesn't work correctly since it considers QualifiedResourcePaths and ResourcePaths as non-equal. Our typings already ensure that a FieldPath and a ResourcePath can never be compared for equality.
Fixes https://github.com/googleapis/nodejs-firestore/issues/1098
=> fix: return null for 'parent' call on root collection

dev/src/index.ts
We need to modify the local settings objects to ensure that the authorization header is sent with every request.
Fixes https://github.com/googleapis/nodejs-firestore/issues/1104
=> fix: send Authentication header with every emulator request

dev/conformance/runner.ts, dev/src/bulk-writer.ts, dev/src/document-change.ts, dev/src/document.ts, dev/src/field-value.ts, dev/src/geo-point.ts, dev/src/index.ts, dev/src/path.ts, dev/src/reference.ts, dev/src/serializer.ts, dev/src/timestamp.ts, dev/src/transaction.ts, dev/src/types.ts, dev/src/util.ts, dev/src/watch.ts, dev/src/write-batch.ts, dev/system-test/firestore.ts, dev/test/bulk-writer.ts, dev/test/query.ts, dev/test/util/helpers.ts, dev/test/watch.ts, dev/test/write-batch.ts
This PR updates the code to implement the interfaces for all public types, which should ensure that our API matches our types. It also removes the duplication that we had in `types.ts`, since w can directly depend on the interface types that are defined in our `.d.ts` file.
=> chore: use public API types internally

dev/src/index.ts, dev/src/transaction.ts, dev/src/write-batch.ts, dev/test/write-batch.ts
I would like to remove the code to run a transactional commit on GCF periodically. I hope this code is not needed anymore since the socket timeout has been drastically increased since our beta release and GCF should no longer block our outgoing traffic. On top of that, we never used a transaction runner for these commits, so retries with code ABORTED were not possible. This code was also not added to BulkWriter.
=> fix: remove GCF transaction fallback

dev/src/pool.ts, dev/src/util.ts, dev/src/v1/firestore_admin_client.ts, dev/src/v1/firestore_client.ts, dev/src/v1beta1/firestore_client.ts, dev/system-test/firestore.ts, dev/test/pool.ts
Fixes b/157506412. Turns out there weren't that many places where we were throwing strings.
=> fix: reject all promises with errors

.eslintrc.json, dev/src/bulk-writer.ts
I allowed `console.error` because we pass in `console.error` as the `onError` handler in `Watch.onSnapshot`. 
Should I add this rule to the tests directory as well? If so, should I just c/p the rule, or make another overrides object that includes both `/src` and `/test`?
=> chore: add eslint check for console.log statements

synth.py
Firestore has a different service account than other repos, let's not overwrite it when code generation is functioning again.
=> build: do not overwrite custom env vars

dev/src/backoff.ts, dev/src/watch.ts, dev/test/backoff.ts, dev/test/bulk-writer.ts, dev/test/index.ts, dev/test/query.ts, dev/test/transaction.ts, dev/test/watch.ts
https://github.com/googleapis/nodejs-firestore/issues/1057 describes an issue that we haven't been able to resolve on the backend. It seems that for large Watch snapshots (1000+ documents), the backend sometime stops responding and fails to deliver any further Watch updates. This PR adds a 2 minute timeout that automatically restarts the Watch stream and resumes the Query from the last known state.
The 2 minute timeout is many times larger than the 30 second interval at which Watch is expected to send a target change even if no documents have changed. 
Fixes #1057
=> fix: restart onSnapshot() listeners that stop receiving updates
