- README.md
This adds the appropriate coverage shield to the README.
> Add coverage shield.

- .cloud-repo-tools.json
- LICENSE
- README.md
- package.json
Fixes https://github.com/googleapis/nodejs-firestore/issues/21
> Update the bun dependency to 0.0.12

- package.json
This addresses https://github.com/googleapis/nodejs-firestore/issues/21
> Update bun dependency to 0.0.12

- package.json
I think it's a good idea to release the recent PRs:
- https://github.com/googleapis/nodejs-firestore/commit/0f35bc89ed3ac12a2508d06198a99452b1bc6f72
- https://github.com/googleapis/nodejs-firestore/commit/8a60b4e2cb1b3a09008ea9a662703e28454930e3
- https://github.com/googleapis/nodejs-firestore/commit/c54030f16f4d14cc21ccc159ee73192b310ba21c
- https://github.com/googleapis/nodejs-firestore/commit/d582b2f66a80e263db94bb648a3d554e545e2cf7
- https://github.com/googleapis/nodejs-firestore/commit/d85f33e9b8538f34ac3f2d9a07495bd32a65c325
- https://github.com/googleapis/nodejs-firestore/commit/badcaaea76202f249dc1bea7e6dac86a644d028f
> Preparing 0.8.3 release

- package.json
As discussed offline, some of the validation we added recently can be considered a breaking change.
> Bumping the minor version to 0.9.0

- src/index.js
@stephenplusplus Can you confirm that this indeed what we want and that we don't want to depend on google-proto-files.
> Remove TODO that is no longer applicable

- test/index.js
This should reduce the diff for https://github.com/googleapis/nodejs-firestore/pull/137
> Test refactor

- package.json
- samples/package.json
- (#146) Improving error message for multiple conflicting fields
With this release this package started using `grpc` v1.9.1.
> release v0.13.0

- package.json
- samples/package.json
> Bumping version to v0.13.1

- src/document.js
- types/firestore.d.ts
Fixes some small issues I found while browsing the API docs.
> Fixing API doc

- src/document.js
This ports https://github.com/firebase/firebase-js-sdk/pull/827 from the Mobile Web SDK.
> Allow storing of Object.create(null) data

- src/index.js
- test/index.js
Fixes https://github.com/googleapis/nodejs-firestore/issues/198
> Fixing Query export

- package-lock.json
- package.json
- src/index.js
- src/v1beta1/firestore_client.js
- system-test/firestore.js
Adding `ts-node`, `chai` and `chai-as-promised`. To be used in https://github.com/googleapis/nodejs-firestore/pull/242
> Adding TypeScript dev dependencies

- package.json
- samples/package.json
Bumping version number so that I can prepare the next release.
To be released Sunday night to make the Admin SDK release on Monday.
> Setting version number to v0.15.0

- package.json
- samples/package.json
Going to 15.0.2 due to:
- https://github.com/googleapis/nodejs-firestore/pull/260 (fixed, removed an invalid assert)
- https://github.com/googleapis/nodejs-firestore/pull/261 (fixed, build tool failure)
> Updating version to v0.15.2

- types/firestore.d.ts
Fixes https://github.com/googleapis/nodejs-firestore/issues/271
> Add return type for `settings()` in the .d.ts file

- src/index.js
Fixes https://github.com/googleapis/nodejs-firestore/issues/277
> Fixing Client initialization

- protos/firestore_proto_api.d.ts
- src/field-value.ts
- types/firestore.d.ts
In preparation for ArrayUnion/ArrayRemove.
`protos/firestore_proto_api.d.ts` is copied from the Web client.
> Convert FieldValue to Typescript

- src/backoff.js
- src/index.js
- src/logger.ts
- src/reference.js
- src/validate.js
- src/watch.js
- src/write-batch.js
- test/backoff.js
- test/field-value.ts
- test/util/helpers.ts
- test/watch.js
This moves logger into an external package and frees ExponentialBackoff from its dependency on Firestore.
> Untangle ExponentialBackoff

- package.json
- samples/package.json
This will contain Array-Contains and the Array Transforms.
> Bump Firestore Version to v0.16

- package.json
- samples/package.json
This will be a bugfix release and include:
- https://github.com/googleapis/nodejs-firestore/pull/321
- https://github.com/googleapis/nodejs-firestore/pull/318
- https://github.com/googleapis/nodejs-firestore/pull/319
- https://github.com/googleapis/nodejs-firestore/pull/320
> Bumping version to 0.16.1

- .gitignore
- dev/conformance/runner.ts
- dev/src/convert.ts
- dev/test/index.js
- tsconfig.json
> chore(types): convert a few files to typescript

- dev/src/document-change.ts
- dev/src/document.ts
- dev/src/timestamp.ts
- dev/src/transaction.ts
- dev/src/watch.ts
- dev/system-test/firestore.ts
- tsconfig.json
> fix: improve TypeScript types

- dev/conformance/runner.ts
- dev/src/document.ts
- dev/src/index.ts
- dev/src/logger.ts
- dev/src/path.ts
- dev/src/reference.ts
- dev/src/serializer.ts
- dev/src/transaction.ts
- dev/src/types.ts
- dev/src/write-batch.ts
- dev/system-test/firestore.ts
- dev/test/collection.ts
- dev/test/document.js
- dev/test/index.js
- dev/test/order.js
- dev/test/query.js
- dev/test/timestamp.js
- dev/test/transaction.js
- dev/test/typescript.ts
- dev/test/util/helpers.ts
- dev/test/watch.js
- dev/test/write-batch.js
- tsconfig.json
- types/firestore.d.ts
This converts the last bit of the client code to TS. There are still tests in JS.
I also enabled TSLint for the API test (test/typescript.ts), which uncovered a slew of problems.
> Convert Index and WriteBatch

- .jsdoc.js
There is no more `src` folder.
> Fix the root for JSDoc

- dev/src/index.ts
You are welcome. Whoever you might be.
> Make default exports work again

- samples/package.json
- samples/quickstart.js
- samples/system-test/quickstart.test.js
> docs: convert samples to async/await

- .kokoro/continuous/node11/common.cfg
- .kokoro/presubmit/node11/common.cfg
- .kokoro/samples-test.sh
- .kokoro/system-test.sh
See https://github.com/googleapis/synthtool/pull/110
> build: run tests on node11

- dev/src/timestamp.ts
- dev/src/write-batch.ts
> docs: update doc writetime

- dev/src/transaction.ts
> docs: fix indexing in docstr

- dev/src/reference.ts
> docs: Elaborate on QuerySnapshot.forEach

- dev/test/transaction.ts
This is part of #512  but can be reviewed independently.
This PR adds type information to the transaction test.
> refactor: Add strict types for the transaction test

- CHANGELOG.md
- package.json
- samples/package.json
> Release @google-cloud/firestore v1.0.1

- CHANGELOG.md
- package.json
- samples/package.json
> Release @google-cloud/firestore v1.0.2

- CHANGELOG.md
- package.json
- samples/package.json
> Release @google-cloud/firestore v1.1.0

- CHANGELOG.md
- package.json
- samples/package.json
> Release @google-cloud/firestore v1.2.0

- CHANGELOG.md
- package.json
- samples/package.json
> Release @google-cloud/firestore v1.3.0

- .nycrc
> build: Exclude Proto files from Coverage

- package.json
See https://github.com/googleapis/nodejs-firestore/pull/648
> deps: Remove dependency on lodash.merge

- .idea/runConfigurations/Conformance_Tests.xml
- .idea/runConfigurations/System_Test.xml
- .idea/runConfigurations/Unit_Tests.xml
This PR adds three test runners (unit, conformance, system-test) to make it easier for IntelliJ users to develop on this repo. VSCode runners are coming soon.
> Add IntelliJ test runners

- CHANGELOG.md
- package.json
- samples/package.json
> Release @google-cloud/firestore v2.1.1

- dev/src/field-value.ts
> docs: Adding example for FieldValue.isEqual

- dev/src/serializer.ts
- dev/src/util.ts
- dev/test/document.ts
Fixes firebase/firebase-admin-node#548
> fix: Store large numbers as doubles

- dev/src/reference.ts
- dev/test/query.ts
Fixes https://github.com/firebase/firebase-admin-node/issues/608
> fix: Better error for Collection Group Queries with documentId() cursors

- samples/solution-counters.js
- samples/test/solution-counters.test.js
Sample for Distributed Counters concepts.
Samples for Distributed Counters in other languages:
https://firebase.google.com/docs/firestore/solutions/counters
Continuation of: [Go samples](https://github.com/GoogleCloudPlatform/golang-samples/pull/959), [Python samples](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2412).
> sample: sample for distributed counters

- dev/protos/firestore_admin_v1_proto_api.d.ts
- dev/protos/firestore_admin_v1_proto_api.js
- dev/protos/firestore_v1_proto_api.d.ts
- dev/protos/firestore_v1_proto_api.js
- dev/protos/firestore_v1beta1_proto_api.d.ts
- dev/protos/firestore_v1beta1_proto_api.js
- dev/protos/insert-license.sh
- dev/protos/update.sh
This should fix the License check CI.
> fix: add license to generated protos

- dev/src/pool.ts
> fix: remove redundant log line

- dev/src/index.ts
> docs: update documentation for preconditions

- dev/system-test/firestore.ts
Fixes https://github.com/googleapis/nodejs-firestore/issues/977
This brings the test in line with https://github.com/schmidt-sebastian/java-firestore/blob/master/google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java#L536
> fix: fix flaky contention test

- dev/src/util.ts
Reverts googleapis/nodejs-firestore#984
> Revert "Use Random Number from `crypto` to generate AutoId."

- dev/src/field-value.ts
- dev/test/field-value.ts
> fix: validate nested arrays in FieldValue

- dev/protos/update.sh
sed -i (in-place replace) only exists on Mac
> fix: make update.sh work on Linux

- dev/src/index.ts
I thought I pushed my changes before merging into master, but it turns out I didn't :(
> fix: Fix BulkWriter comments

- dev/src/serializer.ts
- package.json
This breaks my local build since Moment cannot be resolved and also breaks CI:
https://github.com/googleapis/nodejs-firestore/pull/1062/checks?check_run_id=637099360
> fix: remove type dependency on Moment

- .github/CODEOWNERS
> fix: Point to team in correct org

- dev/src/reference.ts
- types/firestore.d.ts
FIxes https://github.com/googleapis/nodejs-firestore/issues/1090
> docs: specify that select() cannot be used with listeners

- dev/src/index.ts
This fixes https://github.com/firebase/firebase-js-sdk/issues/3105#issuecomment-635541894.
Before this change, `db.settings({..., ssl: false})` will connect but without any credentials (similar to a client device that is not logged in), which causes Firestore Emulator to evaluate security rules for requests. This is surprising for an Admin SDK and it is extremely hard to troubleshoot.
After this change, the same code should correctly behave like admin. This also provides one additional way to get admin privileges in the Firestore Emulator if for some reasons the environment variables is not viable / desirable.
> fix: authenticate as admin user when ssl:false is set

- samples/test/limit-to-last-query.test.js
Fixes https://github.com/googleapis/nodejs-firestore/issues/1226
> tests: fix LimitToLast quickstart
